/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_tmp_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};

/* C:(i0[9])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a4, a5, a6, a7, a8, a9;
  a0=4.8035536718039595e-08;
  a1=4.8965888601467475e-12;
  a2=arg[0] ? arg[0][3] : 0;
  a3=cos(a2);
  a4=(a1*a3);
  a2=sin(a2);
  a4=(a4+a2);
  a5=2.;
  a6=9.8100000000000005e+00;
  a7=2.0682310711021444e-13;
  a8=(a7*a3);
  a9=1.0127277222968137e-24;
  a10=(a9*a2);
  a8=(a8-a10);
  a10=(a6*a8);
  a11=(a5*a10);
  a12=arg[0] ? arg[0][4] : 0;
  a13=cos(a12);
  a14=(a13*a10);
  a15=-9.8100000000000005e+00;
  a12=sin(a12);
  a16=(a15*a12);
  a14=(a14-a16);
  a16=(a5*a14);
  a17=arg[0] ? arg[0][5] : 0;
  a18=cos(a17);
  a19=(a18*a14);
  a17=sin(a17);
  a10=(a12*a10);
  a15=(a15*a13);
  a10=(a10+a15);
  a15=(a17*a10);
  a19=(a19-a15);
  a15=(a5*a19);
  a20=(a5*a19);
  a21=arg[0] ? arg[0][7] : 0;
  a22=cos(a21);
  a23=(a22*a19);
  a21=sin(a21);
  a24=arg[0] ? arg[0][6] : 0;
  a25=sin(a24);
  a7=(a7*a2);
  a9=(a9*a3);
  a7=(a7+a9);
  a6=(a6*a7);
  a9=(a25*a6);
  a24=cos(a24);
  a14=(a17*a14);
  a26=(a18*a10);
  a14=(a14+a26);
  a26=(a24*a14);
  a9=(a9+a26);
  a26=(a21*a9);
  a23=(a23-a26);
  a26=(a5*a23);
  a23=(a5*a23);
  a26=(a26+a23);
  a23=(a22*a26);
  a19=(a21*a19);
  a27=(a22*a9);
  a19=(a19+a27);
  a27=(a5*a19);
  a28=arg[0] ? arg[0][8] : 0;
  a29=cos(a28);
  a28=sin(a28);
  a30=(a24*a6);
  a31=(a25*a14);
  a30=(a30-a31);
  a31=(a28*a30);
  a32=(a29*a19);
  a31=(a31+a32);
  a31=(a5*a31);
  a32=(a29*a31);
  a33=(a29*a30);
  a19=(a28*a19);
  a33=(a33-a19);
  a33=(a5*a33);
  a19=(a28*a33);
  a32=(a32-a19);
  a27=(a27+a32);
  a32=(a21*a27);
  a23=(a23+a32);
  a20=(a20+a23);
  a15=(a15+a20);
  a23=(a18*a15);
  a14=(a5*a14);
  a9=(a5*a9);
  a22=(a22*a27);
  a21=(a21*a26);
  a22=(a22-a21);
  a9=(a9+a22);
  a22=(a24*a9);
  a21=(a5*a30);
  a30=(a5*a30);
  a29=(a29*a33);
  a28=(a28*a31);
  a29=(a29+a28);
  a30=(a30+a29);
  a21=(a21+a30);
  a30=(a25*a21);
  a22=(a22-a30);
  a14=(a14+a22);
  a22=(a17*a14);
  a23=(a23+a22);
  a16=(a16+a23);
  a23=(a13*a16);
  a10=(a5*a10);
  a22=(a18*a14);
  a30=(a17*a15);
  a22=(a22-a30);
  a10=(a10+a22);
  a22=(a12*a10);
  a23=(a23+a22);
  a11=(a11+a23);
  a4=(a4*a11);
  a23=(a1*a2);
  a23=(a23-a3);
  a22=(a5*a6);
  a30=(a5*a6);
  a5=(a5*a6);
  a6=(a24*a21);
  a29=(a25*a9);
  a6=(a6+a29);
  a5=(a5+a6);
  a30=(a30+a5);
  a22=(a22+a30);
  a23=(a23*a22);
  a4=(a4+a23);
  a23=-4.8965888601467475e-12;
  a6=-981.;
  a29=(a23*a3);
  a29=(a29-a2);
  a29=(a29*a22);
  a2=(a23*a2);
  a3=(a3+a2);
  a3=(a3*a11);
  a29=(a29-a3);
  a3=-2.0682310711021444e-13;
  a2=-1.9620000000000001e+01;
  a10=(a13*a10);
  a16=(a12*a16);
  a10=(a10-a16);
  a2=(a2+a10);
  a3=(a3*a2);
  a29=(a29+a3);
  a3=(a1*a29);
  a10=1.0006200000000000e+03;
  a8=(a8*a11);
  a7=(a7*a22);
  a8=(a8+a7);
  a8=(a8-a2);
  a10=(a10+a8);
  a3=(a3-a10);
  a6=(a6+a3);
  a23=(a23*a6);
  a4=(a4+a23);
  a23=2.3976582465313225e-23;
  a6=4.8035536718039594e-09;
  a1=(a1*a10);
  a29=(a29+a1);
  a6=(a6+a29);
  a23=(a23*a6);
  a4=(a4+a23);
  a0=(a0+a4);
  a0=(-a0);
  if (res[0]!=0) res[0][0]=a0;
  a6=(-a6);
  if (res[0]!=0) res[0][1]=a6;
  if (res[0]!=0) res[0][2]=a10;
  a10=-3.5000000000000003e-02;
  a6=(a10*a24);
  a6=(a6*a21);
  a0=(a10*a25);
  a0=(a0*a9);
  a6=(a6+a0);
  a0=(a18*a6);
  a4=-6.7000000000000004e-01;
  a23=(a4*a24);
  a23=(a23*a21);
  a4=(a4*a25);
  a4=(a4*a9);
  a23=(a23+a4);
  a4=(a17*a23);
  a0=(a0+a4);
  a12=(a12*a0);
  a6=(a17*a6);
  a23=(a18*a23);
  a6=(a6-a23);
  a23=6.8000000000000005e-01;
  a5=(a23*a5);
  a6=(a6+a5);
  a13=(a13*a6);
  a12=(a12+a13);
  a13=2.6000000000000001e-01;
  a13=(a13*a30);
  a12=(a12+a13);
  a12=(-a12);
  if (res[0]!=0) res[0][3]=a12;
  a10=(a10*a20);
  a20=6.7000000000000004e-01;
  a25=(a20*a25);
  a25=(a25*a21);
  a10=(a10+a25);
  a20=(a20*a24);
  a20=(a20*a9);
  a10=(a10-a20);
  a17=(a23*a17);
  a17=(a17*a15);
  a17=(a10+a17);
  a23=(a23*a18);
  a23=(a23*a14);
  a17=(a17-a23);
  if (res[0]!=0) res[0][4]=a17;
  if (res[0]!=0) res[0][5]=a10;
  a10=0.;
  if (res[0]!=0) res[0][6]=a10;
  if (res[0]!=0) res[0][7]=a10;
  if (res[0]!=0) res[0][8]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int C(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void C_incref(void) {
}

CASADI_SYMBOL_EXPORT void C_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int C_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int C_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* C_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* C_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* C_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* C_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int C_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
