/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_tmp_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};

/* C:(i0[2],i1[2])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][1] : 0;
  a1=sin(a0);
  a2=arg[1] ? arg[1][1] : 0;
  a3=4.2734670000000004e-06;
  a4=(a3*a2);
  a5=-5.0272982999999998e-04;
  a6=arg[1] ? arg[1][0] : 0;
  a7=(a1*a6);
  a8=(a5*a7);
  a4=(a4-a8);
  a8=1.1763977942999999e-02;
  a0=cos(a0);
  a9=(a0*a6);
  a10=(a8*a9);
  a4=(a4+a10);
  a10=(a2*a4);
  a11=1.5218160428000000e-02;
  a11=(a11*a2);
  a12=7.1173367799999999e-04;
  a13=(a12*a7);
  a11=(a11-a13);
  a13=(a3*a9);
  a11=(a11+a13);
  a13=(a9*a11);
  a10=(a10-a13);
  a13=1.2411765597000000e-02;
  a14=(a9*a2);
  a15=(a13*a14);
  a16=(a7*a2);
  a17=(a5*a16);
  a15=(a15+a17);
  a10=(a10-a15);
  a10=(a1*a10);
  a15=(a5*a14);
  a8=(a8*a16);
  a15=(a15+a8);
  a8=(a12*a2);
  a13=(a13*a7);
  a8=(a8-a13);
  a5=(a5*a9);
  a8=(a8+a5);
  a5=(a2*a8);
  a11=(a7*a11);
  a5=(a5+a11);
  a15=(a15+a5);
  a15=(a0*a15);
  a10=(a10+a15);
  a15=-4.9000000000000002e-02;
  a0=(a15*a0);
  a5=4.4035999999999997e-01;
  a15=(a15*a1);
  a1=(a15*a6);
  a11=(a1*a2);
  a11=(a5*a11);
  a13=(a5*a1);
  a17=(a2*a13);
  a11=(a11-a17);
  a11=(a0*a11);
  a10=(a10+a11);
  a0=(a0*a6);
  a6=(a5*a0);
  a11=(a2*a6);
  a2=(a0*a2);
  a5=(a5*a2);
  a11=(a11-a5);
  a15=(a15*a11);
  a10=(a10+a15);
  a10=(-a10);
  if (res[0]!=0) res[0][0]=a10;
  a9=(a9*a8);
  a7=(a7*a4);
  a9=(a9+a7);
  a1=(a1*a6);
  a9=(a9+a1);
  a0=(a0*a13);
  a9=(a9-a0);
  a12=(a12*a14);
  a3=(a3*a16);
  a12=(a12+a3);
  a9=(a9-a12);
  if (res[0]!=0) res[0][1]=a9;
  return 0;
}

CASADI_SYMBOL_EXPORT int C(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void C_incref(void) {
}

CASADI_SYMBOL_EXPORT void C_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int C_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int C_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* C_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* C_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* C_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* C_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int C_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
